# -*- coding: utf-8 -*-
"""Med_Post_#4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYGnf3E-YkSthaIo0wGO1zDqtqBpq2fb
"""

#Importing all necessary packages
import pandas as pd
import numpy as np
import re
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt


#Loading car dataset
df = pd.read_csv("transfermarkt_players.csv")

#Exploring the dataset
#Check what columns we have
print(df.columns)

#Checking data types for columns
print(df.dtypes)

#Cleaning Data for Analysis (More specifcially the "Value" column)
def parse_value(s):
  if not isinstance(s, str): return None
  m = re.match(r'[€$£]?([\d.]+)([kmb]?)', s.strip().lower())
  return float(m.group(1)) * {'k': 1e3, 'm': 1e6, 'b': 1e9}.get(m.group(2), 1) if m else None

df['value_clean'] = df['value'].apply(parse_value)

df['position'].unique()

"""# Filtering & Preparing Data"""

# 1. Filter for the specific attacking positions you identified
attack_positions = ['Second Striker', 'Right Winger', 'Left Winger', 'Centre-Forward']
attackers = df[df['position'].isin(attack_positions)].copy()

# 2. Select our features for the similarity analysis
features = ['goals', 'assists', 'value_clean']

# 3. Drop rows with missing values in these features to ensure the math works
data_clean = attackers.dropna(subset=features).copy()

print(f"Total attackers ready for clustering: {len(data_clean)}")

"""# Elbow Method"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(data_clean[features])

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method: Finding Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.grid(True)
plt.show()

"""# Clusters"""

#Apply K-Means with k=4
kmeans = KMeans(n_clusters=4, init='k-means++', random_state=42, n_init=10)
data_clean['cluster'] = kmeans.fit_predict(X_scaled)

#Characterizing clusters and finding examples
# Create a copy for display so we don't mess up our actual data
display_df = data_clean.copy()

# Convert the big numbers into a readable "Millions" format
display_df['Value (€M)'] = display_df['value_clean'].apply(lambda x: f"€{x/1_000_000:.1f}M")

print("--- CLUSTER ANALYSIS: TOP 5 PRODUCERS ---")

for cluster_id in range(4):
    subset = display_df[display_df['cluster'] == cluster_id]

    avg_goals = subset['goals'].mean()
    avg_val = subset['value_clean'].mean()

    print(f"\n{'='*45}")
    print(f"CLUSTER {cluster_id}")
    print(f"Avg Goals: {avg_goals:.2f} | Avg Value: €{avg_val/1_000_000:.1f}M")
    print(f"{'-'*45}")

    # Sort by goals and show the readable columns
    top_5 = subset.sort_values(by='goals', ascending=False).head(5)
    print(top_5[['name', 'goals', 'assists', 'Value (€M)']].to_string(index=False))

"""# Visualization"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=data_clean, x='goals', y='value_clean', hue='cluster', palette='viridis', s=100)
plt.title('Player Clusters: Production vs. Market Value')
plt.xlabel('Goals Scored')
plt.ylabel('Market Value (Euro)')
plt.yscale('log') # Log scale helps see the spread better
plt.legend(title='Cluster')
plt.show()